extends RefCounted

## Chinese source text is a stable display key, never a replacement pattern.
const TEXTS: Dictionary = {
	"移动；相反方向同时按住时，后按优先": "Move; the last pressed direction takes priority",
	"短按低跳，长按高跳；羽翼增加空跳": "Tap for a low jump, hold for height; Feathers add air jumps",
	"返回战场": "Back to Battle",
	"获得遗物 · %s · %s": "Relic Acquired · %s · %s",
	"已装备 · %s · %s": "Equipped · %s · %s",
	"超频芯片": "Overclock Chip",
	"裂变电容": "Fission Capacitor",
	"棱镜目镜": "Prism Lens",
	"共生核心": "Symbiotic Core",
	"矢量推进器": "Vector Thruster",
	"电弧线圈": "Arc Coil",
	"余烬孢子": "Ember Spore",
	"星苔": "Star Moss",
	"虹吸针": "Siphon Needle",
	"低温回路": "Coolant Circuit",
	"跃迁羽翼": "Phase Feather",
	"脆晶契约": "Glass Pact",
	"陶瓷装甲": "Ceramic Plating",
	"牵引磁环": "Magnetic Ring",
	"丰收协议": "Harvest Protocol",
	"静息电池": "Resting Battery",
	"霜凝结晶": "Frost Crystal",
	"惯性飞轮": "Momentum Flywheel",
	"蚀骨菌株": "Corrosive Culture",
	"第六回声": "Sixth Echo",
	"穿界针": "Phase Piercer",
	"广域共鸣器": "Wideband Resonator",
	"不灭余火": "Phoenix Ember",
	"超新星种子": "Nova Seed",
	"脉冲步枪": "Pulse Rifle",
	"共鸣弧刃": "Resonance Blade",
	"裂片霰弹枪": "Shattergun",
	"穿星磁轨枪": "Starpiercer Railgun",
	"熔火喷流": "Flamethrower",
	"回旋星刃": "Returning Starblade",
	"万雷权杖": "Storm Staff",
	"恒星长矛": "Sun Lance",
	"震荡手雷": "Concussion Grenade",
	"裂地冲击": "Groundbreaker",
	"共生修复场": "Repair Field",
	"相位护盾": "Phase Aegis",
	"引力囚笼": "Gravity Cage",
	"哨戒构装": "Sentry Construct",
	"天穹陨击": "Meteor Strike",
	"时序王冠": "Chrono Crown",
	"每层 +13% 普通攻击速度。": "+13% primary attack speed per stack.",
	"每层 +12% 伤害，武器与伤害型主动装备均生效。": "+12% damage per stack for weapons and damaging active equipment.",
	"每层 +8% 暴击率（上限85%）；暴击造成双倍伤害。": "+8% critical chance per stack, up to 85%. Critical hits deal double damage.",
	"每层 +25 基础最大生命，获得时回复增加的生命；受脆晶倍率影响。": "+25 base maximum health per stack. Gaining a stack heals the added health; Glass Pact's multiplier applies.",
	"每层 +9% 移速，并缩短冲刺冷却。": "+9% movement speed per stack and a shorter dash cooldown.",
	"命中概率向最多3个邻敌弹射电弧；叠层提高概率和伤害，电弧不再次触发。": "Hits can chain lightning to up to 3 nearby enemies. Stacks increase the chance and damage; lightning cannot trigger itself.",
	"直接击杀产生115范围爆炸；每层 +9 爆炸伤害，连锁击杀不再爆炸。": "Direct kills explode in a 115 radius. Each stack adds 9 explosion damage; chain kills do not explode again.",
	"每层每秒回复0.65生命；5秒未受伤时翻倍。": "Restore 0.65 health per second per stack, doubled after 5 seconds without taking damage.",
	"每层击杀回复1.8生命。": "Kills restore 1.8 health per stack.",
	"每层缩短主动装备冷却；最低为基础冷却的35%。": "Each stack reduces active equipment cooldowns, down to 35% of the base cooldown.",
	"每层增加1次空中跳跃。落地后恢复所有跳跃次数，可跨越阶梯走捷径。": "Each stack grants 1 extra air jump. Landing restores all jumps; use them to skip steps and take shortcuts.",
	"每层 +30% 伤害；每层将最大生命乘以0.85（最低为角色基础生命的20%）。": "+30% damage per stack. Each stack multiplies maximum health by 0.85, down to 20% of your character's base health.",
	"代价：立即降低最大生命！当前生命超过新上限时会被截断；叠层会继续降低。": "Cost: immediately reduces maximum health! Current health above the new maximum is lost. Further stacks reduce it again.",
	"每层抵消1点受到的伤害，最多抵消该次伤害的60%。": "Reduce incoming damage by 1 per stack, up to 60% of each hit.",
	"每层增加35范围的治疗自动收集距离，上限350；金币自动到账，遗物仍需手动拾取。": "+35 healing pickup radius per stack, up to 350. Gold is credited automatically; relics still require manual pickup.",
	"击杀金币每层增加15%，最多翻倍；采用存活队员的最高加成，全队自动到账。首领固定奖金不加成。": "+15% kill gold per stack, up to double. The best living teammate's bonus applies to the whole squad automatically. Fixed boss bonuses are unaffected.",
	"6秒未受伤后每秒恢复护盾，每层最高8点；总上限为最大生命60%。": "After 6 seconds without taking damage, regenerate shield over time: up to 8 shield per stack, capped at 60% of maximum health.",
	"直接命中使敌人减速1.5秒；首层20%，每额外层+5%，上限50%。": "Direct hits slow enemies for 1.5 seconds: 20% for the first stack, +5% per additional stack, up to 50%.",
	"冲刺后1.2秒内每层 +15%伤害，最多+60%。": "Dashing grants +15% damage per stack for 1.2 seconds, up to +60%.",
	"直接命中附加4秒中毒，每层每秒3伤害，最多按8层计算；持续伤害不触发连锁。": "Direct hits poison for 4 seconds, dealing 3 damage per second per stack, up to 8 stacks. Damage over time does not trigger chains.",
	"每第6次普通攻击追加自动共鸣打击，每层12伤害（最多8层），搜索范围650。": "Every 6th primary attack adds an automatic resonance strike within 650 range: 12 damage per stack, up to 8 stacks.",
	"非爆炸弹丸每层多穿透1个目标，最多增加3次；同次飞行不重复命中。": "Non-explosive projectiles pierce 1 extra target per stack, up to 3 extra targets. Each flight hits a target only once.",
	"首层使自己的伤害爆炸半径增加30%，后续每层再增加10%，最多增加80%。": "Your damaging explosions gain 30% radius with the first stack, then +10% per additional stack, up to +80%.",
	"每层每关可抵挡1次致命伤（最多2次），恢复35%生命并获得2秒无敌。": "Prevent 1 lethal hit per stack per stage, up to 2 times. Restore 35% health and gain 2 seconds of invulnerability.",
	"直接暴击释放130范围新星，每层16伤害（最多8层）；0.75秒内置冷却，不递归触发。": "Direct critical hits release a nova in a 130 radius: 16 damage per stack, up to 8 stacks. Has a 0.75-second internal cooldown and cannot trigger itself.",
	"精准持续射击：每发8伤害，基础间隔0.19秒；中远距离稳定火力。": "Accurate sustained fire: 8 damage per shot, one shot every 0.19 seconds. Reliable at medium and long range.",
	"定向近战扇形斩击：基础24伤害，间隔0.52秒；每命中一敌回复0.35生命。": "An aimed melee sweep dealing 24 base damage every 0.52 seconds. Each enemy hit restores 0.35 health.",
	"一次发射6枚散射弹，每枚8伤害，间隔0.60秒；射程约350，贴近目标威力更强。": "Fire 6 pellets for 8 damage each every 0.60 seconds. Range is about 350; strongest at close range.",
	"高能直线穿透弹：基础70伤害，间隔1.05秒；最多穿透3个敌人，射程1500。": "A straight piercing shot dealing 70 base damage every 1.05 seconds. Hits up to 3 enemies at 1500 range.",
	"170范围火焰锥，每0.12秒造成8伤害，并点燃目标：每秒5伤害，持续2秒。": "A flame cone with 170 range deals 8 damage every 0.12 seconds and burns targets for 5 damage per second for 2 seconds.",
	"投出返航刃：每次命中26伤害，往返各可穿透4个目标；间隔0.65秒。": "Throw a returning blade every 0.65 seconds. Each hit deals 26 damage; pierces up to 4 targets on both outward and return flights.",
	"每0.48秒发射32伤害雷球，再向两个邻敌各弹射20伤害；多目标压制。": "Fire a lightning orb every 0.48 seconds for 32 damage, then chain 20 damage each to two nearby enemies.",
	"每0.85秒发射120伤害光矛，最多穿透6敌；每次命中另有70范围22伤害爆裂。": "Fire a 120-damage light lance every 0.85 seconds, piercing up to 6 enemies. Each hit adds a 22-damage blast in a 70 radius.",
	"朝瞄准方向投掷：触敌、落地或0.95秒后爆炸，135范围内基础70伤害。基础冷却8秒。": "Throw toward your aim. Explodes on an enemy, on landing, or after 0.95 seconds for 70 base damage in a 135 radius. Base cooldown: 8 seconds.",
	"向瞄准方向突袭，150范围内基础60伤害，并获得0.45秒无敌。基础冷却9秒。": "Lunge toward your aim, dealing 60 base damage in a 150 radius and gaining 0.45 seconds of invulnerability. Base cooldown: 9 seconds.",
	"立即为260范围内自己与存活队友各回复35%最大生命。基础冷却14秒。": "Immediately restore 35% maximum health to yourself and living teammates within 260 range. Base cooldown: 14 seconds.",
	"获得相当于最大生命60%的护盾，持续6秒，并获得0.4秒无敌。基础冷却12秒。": "Gain shield equal to 60% of maximum health for 6 seconds, plus 0.4 seconds of invulnerability. Base cooldown: 12 seconds.",
	"牵引瞄准点300范围敌人并造成55伤害、定身1.4秒；Boss定身0.45秒。冷却13秒。": "Pull enemies within 300 of the aimed point, dealing 55 damage and immobilizing them for 1.4 seconds, or 0.45 seconds for bosses. Cooldown: 13 seconds.",
	"部署持续8秒炮台，每0.35秒自动向650范围最近敌人发射14伤害弹；最多同时4台。冷却18秒。": "Deploy a turret for 8 seconds. It fires a 14-damage shot every 0.35 seconds at the nearest enemy within 650 range. Up to 4 turrets at once. Cooldown: 18 seconds.",
	"朝瞄准方向300距离召来3次延迟陨击，每次150范围140伤害。冷却22秒。": "Call down 3 delayed meteors 300 units toward your aim. Each deals 140 damage in a 150 radius. Cooldown: 22 seconds.",
	"让350范围内存活队友获得5秒时序加速：攻击速度+60%、移速+30%，并短暂无敌。冷却24秒。": "Living teammates within 350 range gain 5 seconds of time acceleration: +60% attack speed, +30% movement speed, and brief invulnerability. Cooldown: 24 seconds.",
	"普通": "Common",
	"精良": "Uncommon",
	"稀有": "Rare",
	"传说": "Legendary",
	"游侠": "Ranger",
	"先锋": "Vanguard",
	"旅人": "Traveler",
	"旅者": "Traveler",
	"队友": "Teammate",
	"你": "You",
	"初始：脉冲步枪 + 震荡手雷\n100生命；所有武器与主动装备都可在局内替换。": "Starts with: Pulse Rifle + Concussion Grenade\n100 health. All weapons and active equipment can be replaced during a run.",
	"初始：共鸣弧刃 + 裂地冲击\n145生命；所有武器与主动装备都可在局内替换。": "Starts with: Resonance Blade + Groundbreaker\n145 health. All weapons and active equipment can be replaced during a run.",
	"棘背跃兽": "Spineback Pouncer",
	"囊毒喷吐者": "Venom Spitter",
	"孢尘夜蛾": "Spore Moth",
	"晶翼巡猎者": "Crystalwing Hunter",
	"赤岩冲锋兽": "Redrock Charger",
	"砂脊潜伏者": "Sandspine Burrower",
	"棱镜哨卫": "Prism Sentinel",
	"折跃猎手": "Blink Skirmisher",
	"修复导引者": "Repair Conductor",
	"裂岩巨像": "Riftstone Colossus",
	"寂光执政官": "Silentlight Archon",
	"孢冠母巢": "Sporecrown Matriarch",
	"守望者": "Warden",
	"巨木雨林": "Greatwood Rainforest",
	"空心巨木": "Hollow Giant",
	"银雾瀑布": "Silvermist Falls",
	"树冠观测台": "Canopy Observatory",
	"共鸣花冠": "Resonant Crown",
	"折光断崖": "Prismatic Cliffs",
	"废弃升降井": "Abandoned Lift Shaft",
	"回声裂谷": "Echo Chasm",
	"风蚀方尖碑": "Weathered Obelisk",
	"蓝晶矿洞": "Bluecrystal Cavern",
	"风暴灯塔": "Storm Beacon",
	"双环遗迹": "Twinring Ruins",
	"沉睡的共鸣环": "Dormant Resonance Ring",
	"西翼记忆大厅": "West Archive",
	"东翼反应炉": "East Reactor",
	"埋藏墓室": "Buried Crypt",
	"双环之心": "Heart of the Twin Rings",
	"裂隙门": "Rift Gate",
	"信号中断": "SIGNAL LOST",
	"金币": "GOLD",
	"GOLD": "GOLD",
	"界面语言": "Interface Language",
	"语言 / Language": "Language",
	"简体中文": "简体中文",
	"English": "English",
	"首次启动根据系统语言选择": "Your system language is used on first launch.",
	"语言与显示设置已保存。": "Language and display settings saved.",
	"连接超时。请检查地址、端口与防火墙。": "Connection timed out. Check the address, port, and firewall.",
	"无法创建房间：端口 %d 可能已被占用（%s）。": "Could not host: port %d may already be in use (%s).",
	"请输入房主的 IP 地址。": "Enter the host's IP address.",
	"无法连接：%s": "Could not connect: %s",
	"建立连接": "Connecting",
	"正在寻找 %s:%d …": "Looking for %s:%d …",
	"取消": "Cancel",
	"连接失败。请确认房主已创建房间，地址和 UDP 端口正确。": "Connection failed. Make sure the host has opened a room and the address and UDP port are correct.",
	"房主已断开连接，本次对局结束。": "The host disconnected. This run has ended.",
	"当前对局已经开始，请等待房主返回大厅后再加入。": "The run has already started. Wait for the host to return to the lobby before joining.",
	"一位队友离开了远征。": "A teammate has left the run.",
	"房间已满或对局已经开始。": "The room is full or the run has already started.",
	"等待所有队员准备完毕。": "Wait until everyone is ready.",
	"远征开始": "Expedition Begins",
	" · M 地图 · Alt 详情 · 时间会提高威胁": " · M: map · Alt: details · Threat rises over time",
	"%s · M 地图 · Alt 详情 · 时间会提高威胁": "%s · M: map · Alt: details · Threat rises over time",
	"获得遗物 · ": "Relic acquired · ",
	"已装备 · ": "Equipped · ",
	"第 %d 区 · %s": "Area %d · %s",
	"新的远征": "A New Expedition",
	"裂隙已稳定！靠近裂隙门按 E 进入下一关。": "The rift is stable! Approach the gate and press E to continue.",
	"裂隙门已激活。留在附近充能，击败守卫。": "Rift gate activated. Stay nearby to charge it and defeat the guardian.",
	"不灭余火触发 · %s抵挡了一次致命伤。": "Phoenix Ember triggered · %s survived a lethal hit.",
	"正在重建队友的共鸣 …": "Restoring your teammate's resonance …",
	"队友已重返战场。": "Your teammate has returned to the fight.",
	"远征地图": "Expedition Map",
	"雨幕之外，总有另一边。\n一场关于远征、共鸣与生还的合作冒险。": "Beyond the rain, another side awaits.\nA cooperative journey of exploration, resonance, and survival.",
	"游侠 · RANGER": "RANGER",
	"先锋 · VANGUARD": "VANGUARD",
	"当前旅者  /  ": "Current traveler  /  ",
	"当前旅者  /  %s": "Current traveler  /  %s",
	"开始独行     →": "Play Solo     →",
	"创建合作房间": "Host Co-op",
	"加入房间": "Join Room",
	"选择旅者": "Choose Traveler",
	"操作指南": "Controls",
	"设置": "Settings",
	"退出": "Quit",
	"2–4 人合作  /  自由瞄准  /  遗物构筑": "2–4 player co-op  /  Free aiming  /  Relic builds",
	"已远征 %d 次  ·  最远第 %d 区  ·  生还 %d 次": "Runs: %d  ·  Best: Area %d  ·  Wins: %d",
	"01 — THE CANOPY\n巨 木 雨 林": "01 — THE CANOPY\nGREATWOOD RAINFOREST",
	"相同的世界，两种截然不同的生存方式。": "One world. Two ways to survive.",
	"已选中": "Selected",
	"选择": "Select",
	"返回": "Back",
	"加入远征": "Join Expedition",
	"与朋友并肩跨越裂隙。房主需要先创建房间。": "Cross the rift together. Your host must open a room first.",
	"房主 IP 地址": "Host IP Address",
	"例如 192.168.1.20": "e.g. 192.168.1.20",
	"UDP 端口": "UDP Port",
	"连接房间     →": "Connect     →",
	"同一局域网可直接连接。互联网直连需要可达的公网地址与 UDP 端口转发，也可使用虚拟局域网。当前版本通过 IP 加入。": "Connect directly on the same LAN. Over the internet, use a reachable public IP with UDP port forwarding, or a virtual LAN. This version joins rooms by IP address.",
	"队员准备后，由房主启动远征。": "Once everyone is ready, the host can start the run.",
	"远征小队": "Expedition Squad",
	"房主 %s  ·  UDP %d": "Host %s  ·  UDP %d",
	"你的局域网地址  ": "Your LAN address  ",
	"你的局域网地址  %s  :  %d": "Your LAN address  %s  :  %d",
	"准备就绪": "Ready",
	"等待准备": "Not Ready",
	" (你)": " (You)",
	"%02d    等待旅者加入 …": "%02d    Waiting for a traveler …",
	"切换角色": "Change Character",
	"开始远征  →": "Start Expedition  →",
	"取消准备": "Unready",
	"离开房间": "Leave Room",
	"每人独立镜头 · 合作救援 · 三段远征": "Individual cameras · Co-op revives · Three-stage expedition",
	"调整身份、声音与战斗表现。设置自动保存。": "Adjust your name, sound, and combat effects. Changes save automatically.",
	"旅者名称": "Traveler Name",
	"主音量": "Master Volume",
	"特效强度": "Effect Intensity",
	"叠层会增强局部光效；可降低强度或关闭镜头震动。": "Relic stacks intensify effects. Lower the intensity or turn off camera shake here.",
	"镜头震动  ·  ": "Camera Shake  ·  ",
	"镜头震动  ·  %s": "Camera Shake  ·  %s",
	"开启": "On",
	"关闭": "Off",
	"切换窗口 / 全屏  ·  F11": "Window / Fullscreen  ·  F11",
	"生还手册": "Survival Guide",
	"保持移动。瞄准弱点。让遗物产生共鸣。": "Keep moving. Aim carefully. Let your relics resonate.",
	"A / D   或   ← / →": "A / D   or   ← / →",
	"移动；方向与瞄准完全独立": "Move independently of your aim",
	"基础一段跳；跃迁羽翼增加空中跳跃": "One base jump; Phase Feathers add air jumps",
	"穿过脚下的平台": "Drop through the platform beneath you",
	"鼠标左键": "Left Mouse",
	"使用当前主武器，跟随鼠标瞄准": "Use your primary weapon; aim with the mouse",
	"鼠标右键 / Q": "Right Mouse / Q",
	"使用当前主动装备；下方显示冷却": "Use active equipment; its cooldown appears below",
	"移动方向冲刺；静止时朝瞄准方向": "Dash in your movement direction, or toward your aim while still",
	"拾取 / 使用设施 / 激活裂隙门 / 救援": "Pick up / use facilities / activate gates / revive",
	"F   /   按住 Alt": "F   /   Hold Alt",
	"切换附近目标 / 展开道具与装备详情": "Cycle nearby targets / expand item and gear details",
	"构筑 / 地图 / 菜单 / 全屏": "Build / map / menu / fullscreen",
	"三处区域路线不同，按 M 找路，基础单跳即可通行。停留不持续补怪，强度仍随时间增长。遗物图标常驻左下角，悬停查看效果；Tab 查看构筑与图鉴。白 / 绿 / 紫 / 金代表四级稀有度，红字另示代价。裂隙充能并击败守卫后可前进。": "Each area has different routes. Press M for the map; every main route is reachable with one jump. Resting stops ambient reinforcements, but threat still rises over time. Hover over relic icons at the bottom left for effects, or press Tab for your build and the catalog. White / green / purple / gold mark the four rarities; red text shows a cost. Charge the rift and defeat its guardian to advance.",
	"我准备好了": "I'm Ready",
	"左键": "LMB",
	"Q / 右键": "Q / RMB",
	"[Tab] 构筑 / 图鉴  ·  [F] 切换目标  ·  悬停图标查看效果": "[Tab] Build / Catalog  ·  [F] Cycle Target  ·  Hover icons for effects",
	"  ·  [M] 地图": "  ·  [M] Map",
	"停留 · 环境怪不再补充": "Resting · No ambient reinforcements",
	"探索中": "Exploring",
	"事件战斗中": "Event Combat",
	"相位冲刺": "Phase Dash",
	"   +%d 护盾": "   +%d Shield",
	"%02d/03  %02d:%02d  威胁%.1f  ◈%d": "%02d/03  %02d:%02d  Threat %.1f  ◈%d",
	"%02d/03  %02d:%02d  威胁%.1f": "%02d/03  %02d:%02d  Threat %.1f",
	"裂隙 %d%%  ·  %s": "Rift %d%%  ·  %s",
	"击败守卫": "Defeat the Guardian",
	"留在附近充能": "Stay Nearby to Charge",
	"裂隙就绪  ·  靠近按 E 前进": "Rift Ready  ·  Approach and Press E",
	"✚ 待救援": "✚ Awaiting Revive",
	"遗物 %d 件  ·  %d 种": "%d Relics  ·  %d Types",
	"等待队友靠近按 E 救援": "Wait for a teammate to approach and press E to revive",
	" · 已装备": " · Equipped",
	"[Tab] 查看完整构筑": "[Tab] View Full Build",
	"被动遗物  ·  可叠加": "Passive Relic  ·  Stackable",
	"主武器  ·  单一槽位": "Primary Weapon  ·  One Slot",
	"主动装备  ·  单一槽位": "Active Equipment  ·  One Slot",
	"交互设施": "Facility",
	"补给设施  ·  操作前确认代价": "Supply Facility  ·  Check the Cost",
	"替换「%s · %s」；旧装备落地，冷却保留。": "Replace %s · %s. Old gear drops on the ground; cooldowns carry over.",
	"[ E ] 交互": "[ E ] Interact",
	"移开鼠标收起  ·  Tab 查看构筑": "Move the cursor away to close  ·  Tab for Build",
	"松开 Alt 收起": "Release Alt to Close",
	"按住 Alt 查看完整说明": "Hold Alt for Full Details",
	"Space 跳跃 · E 交互 · Tab 背包": "Space: Jump · E: Interact · Tab: Inventory",
	"被动遗物 · 可叠加": "Passive Relic · Stackable",
	"主武器 · 单一槽位": "Primary Weapon · One Slot",
	"主动装备 · 单一槽位": "Active Equipment · One Slot",
	"遗物": "Relic",
	"  ·  已装备": "  ·  Equipped",
	"  ·  未持有": "  ·  Not Owned",
	"旅者构筑": "Traveler Build",
	"%s · %d/%d HP · %d 段跳 · 威胁 %.1f · %d 击破   /   %s": "%s · %d/%d HP · %d Jumps · Threat %.1f · %d Kills   /   %s",
	"合作远征仍在继续": "Co-op Run Continues",
	"远征已暂停": "Run Paused",
	"当前持有": "Owned",
	"遗物图鉴 · %d": "Relics · %d",
	"主武器 · %d": "Weapons · %d",
	"主动装备 · %d": "Active Gear · %d",
	"叠层数量在角标显示；红字表示副作用。": "Badges show stacks; red text marks a drawback.",
	"返回战场  ·  Tab / Esc": "Back to Battle  ·  Tab / Esc",
	"寻找通往高处裂隙的路线，探索分支补给。": "Find a route to the elevated rift and explore branches for supplies. ",
	"合作远征仍在继续。": "The co-op run continues.",
	"远征已暂停。": "The run is paused.",
	"青色 ● 你    蓝色 ● 队友    橙色 ◎ 裂隙门    图标 = 补给设施（暗色表示已使用）": "Teal ● You    Blue ● Teammates    Orange ◎ Rift    Icons = Supplies (dim = used)",
	"返回战场  ·  M / Esc": "Back to Battle  ·  M / Esc",
	"短暂休整": "Take a Breather",
	"雨幕等待你的归来。": "The rain awaits your return.",
	"继续远征": "Resume Expedition",
	"返回主菜单": "Main Menu",
	"Esc 返回  ·  F11 全屏": "Esc: Back  ·  F11: Fullscreen",
	"抵达另一边": "The Other Side",
	"雨幕将你记住": "The Rain Remembers",
	"远征成功。带着共鸣，走向下一个黎明。": "Expedition complete. Carry your resonance into the next dawn.",
	"这一次，旅途止步于此。下一次会更远。": "This journey ends here. The next will go further.",
	"第 %d 区   /   %02d:%02d   /   %d 击破": "Area %d   /   %02d:%02d   /   %d Kills",
	"%s   ·   %d 件遗物   ·   %d 击破": "%s   ·   %d Relics   ·   %d Kills",
	"返回小队大厅": "Squad Lobby",
	"等待房主返回大厅，可再次出发。": "Wait for the host to return to the lobby to start again.",
	"再次出发     →": "Try Again     →",
	"救援 · ": "Revive · ",
	"救援 · %s": "Revive · %s",
	"靠近按 E 启动1.8秒重建；队友恢复55%生命。全员倒下则救援中止。": "Approach and press E to begin a 1.8-second revive. Your teammate returns with 55% health. A full squad wipe cancels the revive.",
	"E · 启动救援": "E · Start Revive",
	"正在重建 · %.1f秒": "Reviving · %.1fs",
	"共鸣已稳定。全队进入下一关并恢复生命。": "Resonance stabilized. The squad advances to the next area with health restored.",
	"最终共鸣已稳定，完成远征。": "The final resonance is stable. Complete the expedition.",
	"E · 前往下一关": "E · Next Area",
	"E · 完成远征": "E · Complete Expedition",
	"留在640范围内完成充能，并击败裂隙守卫。": "Stay within 640 range to finish charging and defeat the rift guardian.",
	"充能 %d%% · %s": "Charge %d%% · %s",
	"守卫仍在": "Guardian Alive",
	"守卫已击败": "Guardian Defeated",
	"召唤守卫并开始22秒共鸣充能。准备妥当后启动。": "Summon the guardian and begin a 22-second charge. Activate when ready.",
	"E · 激活裂隙门": "E · Activate Rift",
	"E · 拾取遗物": "E · Take Relic",
	"E · 替换主武器": "E · Swap Weapon",
	"E · 替换主动装备": "E · Swap Active Gear",
	"将替换「%s」，旧装备会落地；换装保留未结束的冷却。": "Replaces %s. Your old gear drops on the ground; unfinished cooldowns carry over.",
	"当前装备": "Current Gear",
	"生命献祭 · ": "Blood Offering · ",
	"生命献祭 · %s": "Blood Offering · %s",
	"生命献祭": "Blood Offering",
	"消耗%d当前生命（不会致死），奖励落地后再按E选择。\n": "Spend %d current health without dying. Press E again to select the dropped reward.\n",
	"代价：立即扣除%d当前生命；当前生命必须高于%d。": "Cost: immediately lose %d current health. You must have more than %d health.",
	"E · 献祭 %d 生命": "E · Offer %d Health",
	"试炼信标 · ": "Trial Beacon · ",
	"试炼信标 · %s": "Trial Beacon · %s",
	"试炼信标": "Trial Beacon",
	"召唤4名专属试炼敌人；全部击败后奖励落地。无金币费用。\n": "Summon 4 trial enemies. Defeat all of them to drop the reward. No gold cost.\n",
	"风险：立即进入战斗；周围普通敌人不会计入试炼进度。": "Risk: combat starts immediately. Nearby ambient enemies do not count toward the trial.",
	"E · 开始战斗试炼": "E · Start Trial",
	"试炼进行中 · 剩余 %d": "Trial Active · %d Remaining",
	"三选一商店": "Choice Shop",
	"装备仓": "Equipment Vault",
	"补给箱": "Supply Cache",
	"支付%d金币；奖励落地后再按E选择。\n": "Pay %d gold. Press E again to select the dropped reward.\n",
	"同组三个终端仅可购买一个。\n": "Buy from only one of the three linked terminals.\n",
	"E · 支付 %d 金币": "E · Pay %d Gold",
	"目标已离开范围或已被其他旅者拿走。": "The target is out of reach or another traveler has taken it.",
	"这个设施已被使用。": "This facility has already been used.",
	"地面遗物过多，请先拾取附近物品。": "Too many relics are on the ground. Pick up nearby items first.",
	"生命不足：献祭后必须至少保留1点生命。": "Not enough health: you must have at least 1 health after the offering.",
	"金币不足：需要%d金币。": "Not enough gold: %d required.",
	"当前有其他试炼尚未完成。": "Another trial is still in progress.",
	"24 遗物 · 8 主武器 · 8 主动装备     /     每格显示 64 px 与 24 px 实际图标": "24 Relics · 8 Weapons · 8 Active Items     /     Actual 64 px and 24 px Icons",
	"SOMESIDE / 四阶地面信号": "SOMESIDE / FOUR-TIER LOOT SIGNALS",
	"稀有度由外框、光束和 1–4 个光点表达；图标内部保留物品主题色": "Rarity uses borders, beams, and 1–4 dots; icon interiors retain each item's theme color.",
	"SOMESIDE / 八种武器 · 实际角色与弹道": "SOMESIDE / EIGHT WEAPONS · LIVE CHARACTERS AND PROJECTILES",
	"SOMESIDE / 新主动装备 · 局部战场反馈": "SOMESIDE / ACTIVE EQUIPMENT · IN-WORLD FEEDBACK",
	"金币 %d": "GOLD %d",
	"界面语言  ·  %s": "Interface Language  ·  %s",
	"语言设置": "Language Settings",
	"语言": "Language",
	"自动选择系统语言": "Use System Language",
	"首次启动根据系统语言选择；之后记住你的选择。": "Your system language is used on first launch; your choice is saved after that.",
	"附近目标 %d/%d · F 切换": "Nearby Target %d/%d · F to Cycle",
	"金币不足": "Not Enough Gold",
	"生命不足": "Not Enough Health",
	"已使用": "Used",
	"已装备": "Equipped",
	"未持有": "Not Owned",
	"交互": "Interact",
	"被动遗物": "Passive Relic",
	"主武器": "Primary Weapon",
	"主动装备": "Active Equipment",
	"生命": "Health",
	"护盾": "Shield",
	"威胁": "Threat",
	"显示帧率  ·  %s  /  F3": "Show FPS  ·  %s  /  F3",
	"构筑 / 地图 / 菜单 / 全屏 / 帧率": "Build / map / menu / fullscreen / FPS",
	"Esc 返回  ·  F11 全屏  ·  F3 帧率": "Esc: Back  ·  F11: Fullscreen  ·  F3: FPS",
	"探索、战斗，与朋友一起抵达另一边。": "Explore, fight, and reach the other side together.",
	"当前角色：%s": "Character: %s",
	"单人游戏": "Single Player",
	"选择角色": "Choose Character",
	"选择初始武器与技能；遗物会改变你的战斗方式。": "Choose your starting weapon and skill. Relics shape your build.",
	"输入朋友的房间地址。房主需要先创建房间。": "Enter your friend's address after they create a room.",
	"连接": "Connect",
	"合作房间": "Co-op Lobby",
	"所有玩家准备后，房主即可开始游戏。": "The host can start when everyone is ready.",
	"等待玩家加入": "Waiting for a player",
	"开始游戏": "Start Game",
	"语言、声音与显示。更改自动保存。": "Language, audio, and display. Changes are saved automatically.",
	"基础操作与通关目标。": "Controls and objectives.",
	"背包与图鉴": "Inventory & Codex",
	"游戏菜单": "Game Menu",
	"游戏已暂停。": "Game paused.",
	"继续游戏": "Resume",
	"通关成功": "Run Complete",
	"本局结束": "Run Ended",
	"已完成全部三个区域。": "All three regions cleared.",
	"调整构筑，再次挑战。": "Try a new build and take another run.",
	"区域": "Region",
	"用时": "Time",
	"击破": "Kills",
	"再玩一次": "Play Again",
	"探索、战斗，抵达另一边。": "Explore, fight, and reach the other side.",
	"浏览器版支持单人游玩。2–4 人合作请下载 Windows 版。": "Play solo in your browser. Download the Windows version for 2–4 player co-op.",
	"下载 Windows 版（含联机）": "Download Windows (with co-op)",
	"浏览器单人版  /  自由瞄准  /  遗物构筑": "Browser solo  /  Free aiming  /  Relic builds",
	"此浏览器无法保存设置；关闭页面后更改可能丢失。": "This browser cannot save settings; changes may be lost when you close the page.",
	"切换全屏": "Toggle Fullscreen",
	"构筑 / 地图 / 菜单 / 帧率": "Build / map / menu / FPS",
	"Esc 返回  ·  F3 帧率": "Esc: Back  ·  F3: FPS",
}
